#开发环境配置文件
spring:
  redis:
    database: 0    # Redis数据库索引（默认为0）
    host: r-j6cdgptl2uqv5rtcr0pd.redis.rds.aliyuncs.com    # Redis服务器地址
    port: 6379   # Redis服务器连接端口
    password:  NIcai123456!  # Redis服务器连接密码（默认为空）
    pool:
      max-active: 30    # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8    # 连接池中的最大空闲连接
      min-idle: 0    # 连接池中的最小空闲连接
    timeout: 0    # 连接超时时间（毫秒）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-j6ca4cg6lw713llwgvm.mysql.rds.aliyuncs.com:3306/yex_exchange?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Alchemy@nicai20201216
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
    initialSize: 5 #初始化大小
    minIdle: 5 #最小
    maxActive: 100 #最大
    maxWait: 60000 #配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis : 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true #打开PSCache
    maxPoolPreparedStatementPerConnectionSize: 20 #指定每个连接上PSCache的大小
eureka:
  client:
    service-url:
      defaultZone: http://microservice:123456@localhost:8761/eureka